apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ingress-rules
  namespace: ingress
  labels:
    app: kube-prometheus-stack
    release: monitoring-stack
spec:
  groups:
  - name: ingress.rules
    rules:
    - alert: NginxHighHttp4xxErrorRate
      expr: sum(rate(nginx_ingress_controller_requests{status=~"^4.."}[1m])) / sum(rate(nginx_ingress_controller_requests[1m])) * 100 > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Nginx high HTTP 4xx error rate (instance {{ $labels.instance }})
        description: "Too many HTTP requests with status 4xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
